profiler = SMODS.load_file("src/profiler/profile.lua")()
InputField = SMODS.load_file("src/UI/input_field.lua")() 
SMODS.load_file("src/filter_seeds/pseudorandom.lua")() 
SMODS.load_file("src/filter_seeds/find_next_card.lua")() 
SMODS.load_file("src/filter_seeds/generate_starting_seed.lua")()
SMODS.load_file("src/query_parser/query_parser.lua")() 
SMODS.load_file("src/query_parser/validate_query.lua")()
SMODS.load_file("src/UI/input_multiline_textbox.lua")() 
SMODS.load_file("src/UI/UI.lua")() 
SMODS.load_file("src/main.lua")()