-- SMODS.load_file("src/main.lua")()
-- SMODS.load_file("src/UI/UI.lua")()
-- SMODS.load_file("src/filters/filters.lua")()
-- SMODS.load_file("src/query_parser/query_parser.lua")()

profiler = SMODS.load_file("src/profiler/profile.lua")()
SMODS.load_file("src/profiler/profiler_setup.lua")()
SMODS.load_file("src/filter_seeds/random.lua")() 
SMODS.load_file("src/filter_seeds/find_next_card.lua")() 
SMODS.load_file("src/filter_seeds/generate_starting_seed.lua")() 
SMODS.load_file("src/main.lua")() 